; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon May 02 2022 18:24:05 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5PEI9YKC938:
	dc.w $0, DATA5PEI9YKC938_1-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_2-DATA5PEI9YKC938, DATA5PEI9YKC938_3-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_4-DATA5PEI9YKC938, DATA5PEI9YKC938_5-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_6-DATA5PEI9YKC938, DATA5PEI9YKC938_7-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_8-DATA5PEI9YKC938, DATA5PEI9YKC938_9-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_A-DATA5PEI9YKC938, DATA5PEI9YKC938_B-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_C-DATA5PEI9YKC938, DATA5PEI9YKC938_D-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_E-DATA5PEI9YKC938, DATA5PEI9YKC938_F-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_10-DATA5PEI9YKC938, DATA5PEI9YKC938_11-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_12-DATA5PEI9YKC938, DATA5PEI9YKC938_13-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_14-DATA5PEI9YKC938, DATA5PEI9YKC938_15-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_16-DATA5PEI9YKC938, DATA5PEI9YKC938_17-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_18-DATA5PEI9YKC938, DATA5PEI9YKC938_19-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_1A-DATA5PEI9YKC938, DATA5PEI9YKC938_1B-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_1C-DATA5PEI9YKC938, DATA5PEI9YKC938_1D-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_1E-DATA5PEI9YKC938, DATA5PEI9YKC938_1F-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_20-DATA5PEI9YKC938, DATA5PEI9YKC938_21-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_22-DATA5PEI9YKC938, DATA5PEI9YKC938_23-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_24-DATA5PEI9YKC938, DATA5PEI9YKC938_25-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_26-DATA5PEI9YKC938, DATA5PEI9YKC938_27-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_28-DATA5PEI9YKC938, DATA5PEI9YKC938_29-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_2A-DATA5PEI9YKC938, DATA5PEI9YKC938_2B-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_2C-DATA5PEI9YKC938, DATA5PEI9YKC938_2D-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_2E-DATA5PEI9YKC938, DATA5PEI9YKC938_2F-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_30-DATA5PEI9YKC938, DATA5PEI9YKC938_31-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_32-DATA5PEI9YKC938, DATA5PEI9YKC938_33-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_34-DATA5PEI9YKC938, DATA5PEI9YKC938_35-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_36-DATA5PEI9YKC938, DATA5PEI9YKC938_37-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_38-DATA5PEI9YKC938, DATA5PEI9YKC938_39-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_3A-DATA5PEI9YKC938, DATA5PEI9YKC938_3B-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_3C-DATA5PEI9YKC938, DATA5PEI9YKC938_3D-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_3E-DATA5PEI9YKC938, DATA5PEI9YKC938_3F-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_40-DATA5PEI9YKC938, DATA5PEI9YKC938_41-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_42-DATA5PEI9YKC938, DATA5PEI9YKC938_43-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_44-DATA5PEI9YKC938, DATA5PEI9YKC938_45-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_46-DATA5PEI9YKC938, DATA5PEI9YKC938_47-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_48-DATA5PEI9YKC938, DATA5PEI9YKC938_49-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_4A-DATA5PEI9YKC938, DATA5PEI9YKC938_4B-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_4C-DATA5PEI9YKC938, DATA5PEI9YKC938_4D-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_4E-DATA5PEI9YKC938, DATA5PEI9YKC938_4F-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_50-DATA5PEI9YKC938, DATA5PEI9YKC938_51-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_52-DATA5PEI9YKC938, DATA5PEI9YKC938_53-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_54-DATA5PEI9YKC938, DATA5PEI9YKC938_55-DATA5PEI9YKC938
	dc.w DATA5PEI9YKC938_56-DATA5PEI9YKC938, DATA5PEI9YKC938_57-DATA5PEI9YKC938
DATA5PEI9YKC938_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATA5PEI9YKC938_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA5PEI9YKC938_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA5PEI9YKC938_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATA5PEI9YKC938_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATA5PEI9YKC938_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATA5PEI9YKC938_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATA5PEI9YKC938_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATA5PEI9YKC938_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATA5PEI9YKC938_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATA5PEI9YKC938_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATA5PEI9YKC938_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATA5PEI9YKC938_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATA5PEI9YKC938_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATA5PEI9YKC938_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATA5PEI9YKC938_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATA5PEI9YKC938_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATA5PEI9YKC938_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATA5PEI9YKC938_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATA5PEI9YKC938_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATA5PEI9YKC938_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATA5PEI9YKC938_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATA5PEI9YKC938_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATA5PEI9YKC938_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATA5PEI9YKC938_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATA5PEI9YKC938_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATA5PEI9YKC938_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATA5PEI9YKC938_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATA5PEI9YKC938_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATA5PEI9YKC938_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA5PEI9YKC938_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA5PEI9YKC938_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA5PEI9YKC938_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATA5PEI9YKC938_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA5PEI9YKC938_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA5PEI9YKC938_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATA5PEI9YKC938_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATA5PEI9YKC938_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA5PEI9YKC938_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA5PEI9YKC938_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA5PEI9YKC938_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATA5PEI9YKC938_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA5PEI9YKC938_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA5PEI9YKC938_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATA5PEI9YKC938_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATA5PEI9YKC938_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATA5PEI9YKC938_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA5PEI9YKC938_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATA5PEI9YKC938_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATA5PEI9YKC938_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATA5PEI9YKC938_39: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATA5PEI9YKC938_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATA5PEI9YKC938_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATA5PEI9YKC938_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA5PEI9YKC938_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA5PEI9YKC938_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATA5PEI9YKC938_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA5PEI9YKC938_40: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATA5PEI9YKC938_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA5PEI9YKC938_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATA5PEI9YKC938_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA5PEI9YKC938_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATA5PEI9YKC938_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA5PEI9YKC938_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA5PEI9YKC938_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATA5PEI9YKC938_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATA5PEI9YKC938_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATA5PEI9YKC938_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATA5PEI9YKC938_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATA5PEI9YKC938_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA5PEI9YKC938_4D: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATA5PEI9YKC938_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATA5PEI9YKC938_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATA5PEI9YKC938_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATA5PEI9YKC938_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATA5PEI9YKC938_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATA5PEI9YKC938_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATA5PEI9YKC938_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATA5PEI9YKC938_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATA5PEI9YKC938_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATA5PEI9YKC938_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even